# 配置股票相关的参数
stock:
   inner: # A股
      - sh000001 # 上证ID
      - sz399001 #  深证ID
   outer: # 外盘
      - int_dji # 道琼斯
      - int_nasdaq # 纳斯达克
      - int_hangseng # 恒生
      - int_nikkei # 日经指数
      - b_FSSTI # 新加坡
   marketUrl: https://hq.sinajs.cn/list= #  //大盘参数获取url及个股获取url
   blockUrl: https://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php  #//板块参数获取url

# 定时任务线程池基础参数
task:
   pool:
      corePoolSize: 5 # 核心线程数
      maxPoolSize: 20 # 设置最大线程数
      keepAliveSeconds: 300 # 设置线程活跃时间，单位秒，这里设置的活跃时间其实是临时线程的超时时间
      queueCapacity: 100 # 设置队列容量